### PR TITLE
configures webpack

### PR DESCRIPTION
**Pull request by cawel**
Everything looks good to me, *except* for the fact that clicking on links such as "Resources for beginners" or "Resources for experts" does not work. No errors in the console, and the HTML content is loaded in the DOM as expected. So it seems like the click event handler is not properly registered on that "Resources for beginners" `h2`. 

It looks like a knockout issue. I tried to fix it, but could not within 15min, so I will gently pass it on to you! :)

Note: you need to generate `public/bundle.js` before launching the web server. You build that file like this:

```
npx webpack --config webpack.config.js
```

### CODE REVIEW

**Comment by matstc** [comment]
Thanks @cawel. Although if it doesn't work, I don't think I'll spend any time fixing it. Maybe we can pair on it at some point…

**Comment by matstc** [comment]
Our fix worked but there was an additional error in the HTML (again!).

**Comment by cawel** [comment]
Could you be more specific when you say "an additional error in the HTML"? I'm curious. I examined the [only commit](https://github.com/matstc/whatsnext.info/commit/afd5c7e78820e20ea2df665a6c7357c8abb63f84) after the merge of that PR on the `master` branch and the changes are in js files only, not html files.

**Comment by matstc** [comment]
The fix is in [this commit](https://github.com/matstc/whatsnext.info/commit/004e816a891f1ea85615a2e7ec6c457bd33b5d48). There was an extra apostrophe.

**Pull request merged**
